backend:
  name: test-repo
  branch: master
media_folder: static/uploads
public: uploads
collections:
  - name: "coding"
    label: "Coding"
    folder: "content/coding"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", pattern: ['.{20,}', "Must have at least 20 characters"]}
      - {label: "Published Date", name: "date", widget: "date"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}